#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright (c) 2017, 2018 by Delphix. All rights reserved.
#

---
- name: ensure /var/crash directory exists
  file:
    path: /var/crash
    state: directory
    owner: root
    group: root
    mode: 0755

- name: ensure dumpadm.conf is configured correctly
  lineinfile:
    dest: /etc/dumpadm.conf
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - line: 'DUMPADM_SAVDIR=/var/crash'
      regexp: '^DUMPADM_SAVDIR='
    - line: 'DUMPADM_ENABLE=yes'
      regexp: '^DUMPADM_ENABLE='
  register: dumpadm

- name: reload dumpadm.conf if changed
  command: dumpadm -u
  when: dumpadm.changed

#
# Update Java to the latest version available from the IPS repository.
# The Jenkins Swarm client relies on Java, so we want to ensure we have
# the most recent version installed before we start the Swarm client.
#

- name: refresh IPS repository index
  command: pkg refresh

- name: install lastest OpenJDK 8
  pkg5:
    state: latest
    name:
      - pkg:/developer/java/openjdk8
      - pkg:/runtime/java/openjdk8
  register: result
  until: not result|failed
  retries: 10
  delay: 60
